from Arrow.Tool.generation_management import generated_instruction
from Arrow.Tool.generation_management import generate
from Arrow.Tool.generation_management import generate_x86
from Arrow.Tool.generation_management import generate_riscv
