from Tool.asm_blocks import AsmUnit
from Tool.state_management import get_current_state

# This Class is used to log the assembly code generated by the compiler
class AsmLogger:

    @staticmethod
    def asm(asm_code:str, comment:str=None):
        asm_unit = AsmUnit(asm_string=asm_code, comment=comment)
        current_state = get_current_state()
        current_code_block = current_state.current_code_block
        current_code_block.asm_units_list.append(asm_unit)

    @staticmethod
    def comment(comment: str, add_print:bool = False):
        asm_unit = AsmUnit(comment=comment)
        current_state = get_current_state()
        current_code_block = current_state.current_code_block
        current_code_block.asm_units_list.append(asm_unit)
